package com.dkronig.maswe_crypto.maswe_0025;

/**
 * Data class representing a signed banking command.
 *
 * This class encapsulates all necessary information for a banking operation.
 * Includes the command type, transaction amount, timing information, and a cryptographic
 * signature for verification.
 *
 * Used for communication between the ProfileActivity and BankAccountManagerService.
 */
public class BankCommand {

    /**
     * The banking command to execute (e.g., "increase", "decrease").
     */
    String command;

    /**
     * The transaction amount in euros.
     */
    int amountEuros;

    /**
     * Timestamp of when the command was created (milliseconds).
     */
    float timestamp;

    /**
     * Unique nonce value to prevent replay attacks.
     */
    String nonce;

    /**
     * Cryptographic signature of the command for authenticity verification.
     * Generated by signing the concatenation of command, amount, timestamp, and nonce.
     */
    String signature;
}
