@startuml
'https://plantuml.com/class-diagram
' title "High level view of system architecture"
top to bottom direction
skinparam classAttributeIconSize 0
skinparam dpi 300
skinparam linetype ortho

package "apps" {
    package common {
        rectangle "..." as empty
    }

    package masvs_storage {
        rectangle storage_menu

        together {
               package maswe_0001 {
                   rectangle MainActivity0001
               }

               package maswe_0002 {
                   rectangle MainActivity0002
               }

               rectangle "..." as skipped

               package maswe_0007 {
                   rectangle MainActivity0007
               }
        }
    }

    package masvs_crypto {
        rectangle crypto_menu

        together {

            package maswe_0009 {
                rectangle MainActivity0009
            }

            package maswe_00010 {
                rectangle MainActivity0010
            }

            rectangle "..." as skipped2

            package maswe_00025 {
                rectangle MainActivity0025
            }
        }
    }

    package masvs_platform {
        rectangle platform_menu

        together {
            package maswe_0053 {
                rectangle MainActivity0053
            }

             package maswe_0055 {
                rectangle MainActivity0055
             }

                rectangle "..." as skipped3

            package maswe_00067 {
                rectangle MainActivity0067
            }
        }
    }
}

' Usage
MainActivity0001 <-- storage_menu
MainActivity0002 <-- storage_menu
skipped <-- storage_menu
MainActivity0007 <-- storage_menu


MainActivity0009 <-- crypto_menu
MainActivity0010 <-- crypto_menu
skipped2 <-- crypto_menu
MainActivity0025 <-- crypto_menu


MainActivity0053 <-- platform_menu
MainActivity0055 <-- platform_menu
skipped3 <-- platform_menu
MainActivity0067 <-- platform_menu

' Hidden links to enforce order
MainActivity0001 -[hidden]down- MainActivity0002
MainActivity0002 -[hidden]down- skipped
skipped -[hidden]down- MainActivity0007

MainActivity0009 -[hidden]down- MainActivity0010
MainActivity0010 -[hidden]down- skipped2
skipped2 -[hidden]down- MainActivity0025

MainActivity0053 -[hidden]down- MainActivity0055
MainActivity0055 -[hidden]down- skipped3
skipped3 -[hidden]down- MainActivity0067

' layouts -[hidden]down- "abstract activities"


' Inhertiance
common <|-- masvs_storage
common <|-- masvs_crypto
common <|-- masvs_platform



@enduml